apiVersion: v1
kind: Secret
metadata:
  name: dts-secrets
  namespace: dts-system
  labels:
    app: distributed-timestamp-system
type: Opaque
data:
  # MySQL配置 (base64编码)
  mysql-host: bXlzcWw=  # mysql
  mysql-port: MzMwNg==  # 3306
  mysql-database: Z2ZhZW9mdzg=  # gfaeofw8
  mysql-username: cm9vdA==  # root
  mysql-password: MTIzNDU2  # 123456
  
  # Redis配置 (base64编码)
  redis-host: cmVkaXM=  # redis
  redis-port: NjM3OQ==  # 6379
  redis-password: ""  # 空密码
  
  # Nacos配置 (base64编码)
  nacos-server: bmFjb3M6ODg0OA==  # nacos:8848
  
  # Seata配置 (base64编码)
  seata-server: c2VhdGE6ODA5MQ==  # seata:8091

---
# 用于生产环境的密钥模板（需要替换实际值）
apiVersion: v1
kind: Secret
metadata:
  name: dts-secrets-prod
  namespace: dts-system
  labels:
    app: distributed-timestamp-system
    env: production
type: Opaque
stringData:
  # MySQL配置 - 请替换为实际的生产环境配置
  mysql-host: "mysql-prod.example.com"
  mysql-port: "3306"
  mysql-database: "gfaeofw8"
  mysql-username: "dts_user"
  mysql-password: "CHANGE_ME_MYSQL_PASSWORD"
  
  # Redis配置 - 请替换为实际的生产环境配置
  redis-host: "redis-prod.example.com"
  redis-port: "6379"
  redis-password: "CHANGE_ME_REDIS_PASSWORD"
  
  # Nacos配置 - 请替换为实际的生产环境配置
  nacos-server: "nacos-prod.example.com:8848"
  
  # Seata配置 - 请替换为实际的生产环境配置
  seata-server: "seata-prod.example.com:8091"