apiVersion: v1
kind: Service
metadata:
  name: dts-system-service
  namespace: dts-system
  labels:
    app: distributed-timestamp-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/api/actuator/prometheus"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: distributed-timestamp-system

---
apiVersion: v1
kind: Service
metadata:
  name: dts-system-headless
  namespace: dts-system
  labels:
    app: distributed-timestamp-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: distributed-timestamp-system

---
apiVersion: v1
kind: Service
metadata:
  name: dts-system-nodeport
  namespace: dts-system
  labels:
    app: distributed-timestamp-system
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: distributed-timestamp-system